### ISSUE TITLE
'502 Bad Gateway' often happens in your Docs Web

### ISSUE THREAD

**Issue by iScottMark** [marblestation/iSpec#2]
Hi~ Recently,  I have been always translating your iSpec Docs in Chinese in order to let more scientists or students use this wonderful tool! However, **502 Bad Gateway** often happens, even if I use the 3rd Proxy in U.S. or Hongkong.  So, Plz check whether there is something wrong with your upstream server. Here is the [Chinese Docs URL](https://iscottmark.github.io/iSpec/)

**Comment by marblestation** [comment]
Hi @iScottMark, I know the server has been affected by some attacks recently, maybe that could explain it although I have not seen these 502 errors myself. Thank you so much for your Chinese translation! Let me know when you complete them, maybe I can add a link to them.

**Comment by iScottMark** [comment]
In fact, I only translate the 'Usage' Part which is the most important. They will be done in the next 1 or 2 weeks. You know, I gotta finish my daily study task. 

I am so happy 😄 to receive your reply! I have recommended this tool before to my guys around and they all think it is 👍 user-friendly & functionality-integrated.  ❤️ Thx for your great work again!
