### ISSUE TITLE
Finish All the Translations & Some Other Notes.

### ISSUE THREAD

**Issue by iScottMark** [marblestation/iSpec#3]
@marblestation , Happy Chinese New Year~ :smile:

I have finished all the translations of iSpec docs (including all the 4 parts -- Intro, Install, Usage and Scripting). I know there are still many mistakes, so I choose to deploy the docs in the GitHub/Gitee (Chinese GitHub) pages to allow everyone to edit or correct this docs in Chinese.

- Here is the [project source](https://github.com/iScottMark/iSpec). I use the [VuePress](https://vuepress.vuejs.org/) to build the docs.

- Here is the [Docs](https://iscottmark.github.io/iSpec/).

- For faster access speed in China, here is the [Mirror](https://iscottmark.gitee.io/ispec/).

Besides, I find some links which have failed during my work. I have corrected them in Chinese Docs. They are (the following links are pointed to the location of English Docs):

- VOSpec, [1](https://www.blancocuaresma.com/s/iSpec/manual/introduction/overview), [2](https://www.blancocuaresma.com/s/iSpec/manual/usage/basics)

- Turbospectrum, [1](https://www.blancocuaresma.com/s/iSpec/manual/introduction/overview), [2](https://www.blancocuaresma.com/s/iSpec/manual/usage/synthesis)

However, I accidentally find extra contents about `Any Platform` in the Installation Part but it doesn't show in the left sidebar. I just click the 'Next Arrow' and find them. It confuses me.

In the end, I list a [TODO](https://github.com/iScottMark/iSpec/projects/1) to impove the Docs in the future.

**Comment by marblestation** [comment]
Thank you so much @iScottMark ! I added links to your translation and I corrected the dead links you reported.
