### ISSUE TITLE
Fortran build failure

### ISSUE THREAD

**Issue by dervisoglu** [marblestation/iSpec#7]
Hi Sergi. Today I tried to install ispec to my new laptop with Ubuntu 22.04. But compilation is failed for turbospectrum and moog. Then I found that it is  due to the "new argument type enforcement" of >gfortan 10. It seems the problem is also valid for the latest Fedora distributions. I simply solved the problem by adding "-fallow-argument-mismatch" keyword to the related Makefile's of turbospectrum and moog. I thought it is worth to mention you guys.

Cheers

Ahmet

**Comment by marblestation** [comment]
Thank you! Hopefully, this kind of problems should have been addressed in https://github.com/marblestation/iSpec/commit/cc238a2789bbdd97b21c4987d17a691759ef6a28 committed today!
