### ISSUE TITLE
AttributeError: 'ArtistList' object has no attribute 'remove'

### ISSUE THREAD

**Issue by PsyJim** [marblestation/iSpec#8]
When one tries to close (remove) spectra a warning pops up:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/pochomolo/anaconda3/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/pochomolo/iSpec-master/ispec/gui/iSpecBaseApp.py", line 1302, in on_close_spectrum
    self.axes.lines.remove(self.active_spectrum.plot_id)
AttributeError: 'ArtistList' object has no attribute 'remove'
```

Then the spectra still printed

**Comment by ghost** [comment]
Hey, I had the similar problem. One solution is to create an environment with python 3.8 and matplotlib version 3.6.2.
Hope it helps.

**Comment by marblestation** [comment]
Thank you for pointing this one out! The commit https://github.com/marblestation/iSpec/commit/af620efdfa6c676e3a1be85b3a7830c6b02e10cd should have fixed this 😄
